// client/src/components/Breadcrumb.svelte
<script>
  export let items = [];
</script>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href=".">Permacoop</a>
    </li>
    {#each items as item}
      {#if !item.path}
        <li class="breadcrumb-item active">{item.title}</li>
      {:else}
        <li class="breadcrumb-item">
          <a href={item.path}>{item.title}</a>
        </li>
      {/if}
    {/each}
  </ol>
</nav>

// client/src/modules/core/components/Breadcrumb.tsx
import React from 'react';
import {Link} from 'react-router-dom';
import {BreadcrumbItem} from '../models/BreadcrumbItem';

interface IProps {
  items: BreadcrumbItem[];
}

const Breadcrumb: React.FC<IProps> = ({items}) => {
  return (
    <nav className={'mt-3'}>
      <ol className={'breadcrumb'}>
        <li className={'breadcrumb-item'}>
          <Link to={'/'}>CoopERP</Link>
        </li>

        {items.map((item: BreadcrumbItem, key) => {
          if (item.lastItem) {
            return (
              <li key={key} className={'breadcrumb-item active'}>
                <span className={'active'}>{item.title}</span>
              </li>
            );
          }

          return (
            <li key={key} className={'breadcrumb-item'}>
              <Link to={item.path}>{item.title}</Link>
            </li>
          );
        })}
      </ol>
    </nav>
  );
};

export default Breadcrumb;
