// client/src/components/inputs/TextInput.svelte
<script>
  import shortid from 'shortid';

  export let value;
  export let label;
  export let required = 'required';

  const id = shortid.generate();
</script>

<div class="form-group">
  <label for={id} class={required}>{label}</label>
  <input type="text" {id} {required} bind:value class="form-control" />
</div>

// client/src/modules/core/components/form/TextInput.tsx
import React from 'react';

const TextInput: React.FC = ({
  input,
  label,
  type,
  meta: {touched, error}
}: any) => {
  const inputClass =
    touched && error ? 'form-control is-invalid' : 'form-control';

  return (
    <div className={'form-group row'}>
      <label className={'form-label'}>{label}</label>
      <input {...input} className={inputClass} type={type} />
      {touched && error && (
        <small className={'text-danger form-text'}>{error}</small>
      )}
    </div>
  );
};

export default TextInput;
