// client/src/modules/activity/components/ActivityDetail.tsx
import React from 'react';
import {Badge} from 'react-bootstrap';
import {Link} from 'react-router-dom';
import {IActivity} from '../models/IActivity';
import {dateNormalizer} from '../../../normalizer/date';
import {IActivitiesByDay} from '../models/IActivitiesByDay';

interface IProps {
  activityByDays: IActivitiesByDay;
  canAddActivity: boolean;
}

const ActivityDetail: React.FC<IProps> = ({activityByDays, canAddActivity}) => {
  return (
    <tr className={activityByDays.isWeekend ? 'disabled' : ''}>
      <td>{dateNormalizer(activityByDays.date)}</td>
      <td>
        {activityByDays.activities.map((activity: IActivity) => (
          <div key={activity.id}>
            <Badge variant={'success'}>{activity.taskName}</Badge>{' '}
            <Badge variant={'success'}>{activity.time / 100}</Badge>{' '}
            {activity.projectName}
          </div>
        ))}
      </td>
      <td>
        {true === canAddActivity && false === activityByDays.isWeekend && (
          <Link
            to={`/activities/add/${activityByDays.date}`}
            className={'btn btn-outline-secondary btn-sm'}
          >
            +
          </Link>
        )}
      </td>
    </tr>
  );
};

export default ActivityDetail;

// client-svelte/src/components/activity/ActivityDetail.svelte
<script>
  import {dateNormalizer} from '../../normalizer/date';
  export let day;
</script>

<style>
  tr.disabled {
    background-color: rgba(0, 0, 0, 0.05);
  }
</style>

<tr class={day.isWeekend ? 'disabled' : ''}>
  <td>{dateNormalizer(day.date)}</td>
  <td>
    {#each day.activities as activity}
      <div>
        <span class="badge badge-success">{activity.taskName}</span>
        <span class="badge badge-success">{activity.time / 100}</span>
        {activity.projectName}
      </div>
    {/each}
  </td>
  <td>
    {#if !day.isWeekend}
      <a
        class="btn btn-outline-secondary btn-sm"
        href="/activities/add/2019-12-23">
        +
      </a>
    {/if}
  </td>
</tr>
